on: 
  release:
      types: [published]

name: Deploy
jobs:
  deploy_project:
    runs-on: ubuntu-latest

    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: "readme.md"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -la