on: 
  release:
      types: [published]

name: Deploy
jobs:
  deploy_release:
    runs-on: ubuntu-latest

    steps:
      - id: latest-release
        uses: thebritican/fetch-latest-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -la
      - run: echo ${{ steps.latest-release.outputs.url }}
