on: 
  release:
      types: [published]

name: Deploy
jobs:
  deploy_project:
    runs-on: ubuntu-latest

    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: "readme.md"
      - run: ls -la
      - run: cat readme.md